# SPDX-License-Identifier: GPL-3.0-or-later
services:
  mongo_db:
    image: mongo:latest
    container_name: airbreakerDB
    restart: always
    command: ["--wiredTigerCacheSizeGB", "0.25"] 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s 
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:

  #forntend container will be create in future