# SPDX-License-Identifier: GPL-3.0-or-later
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    
    network_mode: host
    privileged: true
    
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    
    depends_on:
      mongo_db:
        condition: service_healthy
  
    volumes:
      - /sys:/sys
      - /dev:/dev

      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

      - /var/run/wpa_supplicant:/var/run/wpa_supplicant
      - /etc/wpa_supplicant:/etc/wpa_supplicant:ro
  mongo_db:
    image: mongo:latest
    container_name: airbreakerDB
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s 
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:

  #forntend container will be create in future